---
replicaCount: 1

image:
  repository: 149397374544.dkr.ecr.eu-west-1.amazonaws.com/demo-challenge
  pullPolicy: IfNotPresent
  tag: 0.0.1

container:
  env:
    - name: GREET_VAR
      value: Chitrang

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 150m
    memory: 100Mi

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
  minReplicas: 1
  maxReplicas: 5
